# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MainWindow import *
from PyQt5.QtGui import QPixmap

class Ui_ResultsWindow(object):
    def setupUi(self, ResultsWindow):
        ResultsWindow.setObjectName("ResultsWindow")
        ResultsWindow.resize(999, 587)
        ResultsWindow.setStyleSheet("QWidget#centralwidget{ border-image: url(:/newPrefix/ResultsWindow.jpg);}")
        self.centralwidget = QtWidgets.QWidget(ResultsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Summoner = QtWidgets.QLabel(self.centralwidget)
        self.label_Summoner.setGeometry(QtCore.QRect(30, 10, 611, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_Summoner.setFont(font)
        self.label_Summoner.setObjectName("label_Summoner")
        self.label_champs1 = QtWidgets.QLabel(self.centralwidget)
        self.label_champs1.setGeometry(QtCore.QRect(90, 180, 100, 100))
        self.label_champs1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_champs1.setObjectName("label_champs1")
        self.label_champs2 = QtWidgets.QLabel(self.centralwidget)
        self.label_champs2.setGeometry(QtCore.QRect(190, 180, 100, 100))
        self.label_champs2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_champs2.setObjectName("label_champs2")
        self.label_champs3 = QtWidgets.QLabel(self.centralwidget)
        self.label_champs3.setGeometry(QtCore.QRect(290, 180, 100, 100))
        self.label_champs3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_champs3.setObjectName("label_champs3")
        self.label_champs = QtWidgets.QLabel(self.centralwidget)
        self.label_champs.setGeometry(QtCore.QRect(80, 130, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_champs.setFont(font)
        self.label_champs.setAlignment(QtCore.Qt.AlignCenter)
        self.label_champs.setObjectName("label_champs")
        self.label_traits1 = QtWidgets.QLabel(self.centralwidget)
        self.label_traits1.setGeometry(QtCore.QRect(580, 180, 100, 100))
        self.label_traits1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_traits1.setObjectName("label_traits1")
        self.label_traits3 = QtWidgets.QLabel(self.centralwidget)
        self.label_traits3.setGeometry(QtCore.QRect(780, 180, 100, 100))
        self.label_traits3.setStyleSheet("")
        self.label_traits3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_traits3.setObjectName("label_traits3")
        self.label_traits2 = QtWidgets.QLabel(self.centralwidget)
        self.label_traits2.setGeometry(QtCore.QRect(680, 180, 100, 100))
        self.label_traits2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_traits2.setObjectName("label_traits2")
        self.label_traits = QtWidgets.QLabel(self.centralwidget)
        self.label_traits.setGeometry(QtCore.QRect(570, 130, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_traits.setFont(font)
        self.label_traits.setAlignment(QtCore.Qt.AlignCenter)
        self.label_traits.setObjectName("label_traits")
        self.label_items = QtWidgets.QLabel(self.centralwidget)
        self.label_items.setGeometry(QtCore.QRect(310, 300, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_items.setFont(font)
        self.label_items.setAlignment(QtCore.Qt.AlignCenter)
        self.label_items.setObjectName("label_items")
        self.label_items1 = QtWidgets.QLabel(self.centralwidget)
        self.label_items1.setGeometry(QtCore.QRect(320, 350, 100, 100))
        self.label_items1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_items1.setObjectName("label_items1")
        self.label_items3 = QtWidgets.QLabel(self.centralwidget)
        self.label_items3.setGeometry(QtCore.QRect(520, 350, 100, 100))
        self.label_items3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_items3.setObjectName("label_items3")
        self.label_items2 = QtWidgets.QLabel(self.centralwidget)
        self.label_items2.setGeometry(QtCore.QRect(420, 350, 100, 100))
        self.label_items2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_items2.setObjectName("label_items2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 460, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        ResultsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ResultsWindow)
        self.statusbar.setObjectName("statusbar")
        ResultsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ResultsWindow)
        QtCore.QMetaObject.connectSlotsByName(ResultsWindow)

    def retranslateUi(self, ResultsWindow):
        _translate = QtCore.QCoreApplication.translate
        ResultsWindow.setWindowTitle(_translate("ResultsWindow", "MainWindow"))
        self.label_Summoner.setText(_translate("ResultsWindow", "Your Summoner Name"))
        self.label_champs1.setText(_translate("ResultsWindow", "TextLabel"))
        self.label_champs2.setText(_translate("ResultsWindow", "TextLabel"))
        self.label_champs3.setText(_translate("ResultsWindow", "TextLabel"))
        self.label_champs.setText(_translate("ResultsWindow", "Favourite Champions"))
        self.label_traits1.setText(_translate("ResultsWindow", "TextLabel"))
        self.label_traits3.setText(_translate("ResultsWindow", "TextLabel"))
        self.label_traits2.setText(_translate("ResultsWindow", "TextLabel"))
        self.label_traits.setText(_translate("ResultsWindow", "Favourite Traits"))
        self.label_items.setText(_translate("ResultsWindow", "Favourite Items"))
        self.label_items1.setText(_translate("ResultsWindow", "TextLabel"))
        self.label_items3.setText(_translate("ResultsWindow", "TextLabel"))
        self.label_items2.setText(_translate("ResultsWindow", "TextLabel"))
        self.pushButton.setText(_translate("ResultsWindow", "Back to Search Bar"))
import resultswindow_rc

class ResultsWindow(QtWidgets.QMainWindow, Ui_ResultsWindow):
    def __init__(self, parent = None):
        super(ResultsWindow,self).__init__(parent=parent)
        self.setupUi(self)
        self.pushButton.clicked.connect(self.backToMenu)


    def backToMenu(self):
        self.hide()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = ResultsWindow()
    MainWindow.show()
    sys.exit(app.exec_())